"""add_token_version_to_users

Revision ID: 1e7e2f37d0a4
Revises: ab78524075c9
Create Date: 2026-04-25 17:46:10.135864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1e7e2f37d0a4'
down_revision: Union[str, None] = 'ab78524075c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
